
services:
  loginapi:
    image: loginapi
    environment:
     - secretPath=/run/secrets/jwtSecret
    secrets:
     - jwtSecret
    build:
      context: LoginApi
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
      - "7001:8081"
    volumes:
    - ./LoginApi/users.db:/app/users.db

  gameserverapi:
    image: gameserverapi
    environment:
     - secretPath=/run/secrets/jwtSecret 
    secrets:
     - jwtSecret
    build:
      context: GameServerAPI
      dockerfile: Dockerfile
    ports:
      - "7002:8080"
      - "7003:8081"

  chatapi:
    image: chatapi
    build: 
     context: ChatAPI
     dockerfile: Dockerfile
    ports:
    - "7004:8080"
    - "7005:8081"

  sessionapi:
    image: sessionapi
    build:
      context: SessionAPI
      dockerfile: Dockerfile


secrets:
  jwtSecret:
   file: ./secret.txt
