services:
  loginapi:
    image: ${DOCKER_REGISTRY-}loginapi
    ports:
    - "7000:80"
    - "7001:443"
    build:
      dockerfile: LoginAPI/Dockerfile
  gameserverapi:
    image: ${DOCKER_REGISTRY-}gameserverapi
    build:
      dockerfile: GameserverAPI/Dockerfile
  sessionapi:
    image: ${DOCKER_REGISTRY-}sessionapi
    build:
      dockerfile: SessionAPI/Dockerfile
 
