
services:
  loginapi:
    image: loginapi
    build:
      context: LoginApi
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
      - "7001:8081"
    volumes:
    - ./LoginApi/users.db:/app/users.db
  gameserverapi:
    image: gameserverapi
    build:
      context: GameServerAPI
      dockerfile: Dockerfile

  sessionapi:
    image: sessionapi
    build:
      context: SessionAPI
      dockerfile: Dockerfile

